artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.9.5
    provides:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.6.4
  "@daiyam/artifact-npm-ts":
    version: 0.4.3
  "@daiyam/artifact-npm-zokugun":
    version: 0.2.2
